name: BUILD CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Lint
      run: yarn lint
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '7.0'
        mongodb-replica-set: rs0
        mongodb-port: 27017
    
    - name: Build Docker image
      run: docker build -t merch-service-api:${{ github.sha }} -f Dockerfile.prod .
    
    - name: Test Docker image
      run: |
        docker run --rm merch-service-api:${{ github.sha }} echo "Docker image built successfully"

    - name: Login to Heroku Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.heroku.com
        username: ${{ secrets.HEROKU_EMAIL }}
        password: ${{ secrets.HEROKU_API_KEY }}
        
    - name: Build and push to Heroku
      env:
        HEROKU_APP_NAME: project-cloud-service
      run: |
        docker tag merch-service-api:${{ github.sha }} registry.heroku.com/$HEROKU_APP_NAME/web
        
        docker push registry.heroku.com/$HEROKU_APP_NAME/web
        
    - name: Release to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: project-cloud-service
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        
        heroku container:release web --app=$HEROKU_APP_NAME